### ISSUE TITLE
datareader not parsing results correctly

### ISSUE THREAD

**Issue by WK-eni** [Faithlife/System.Data.SQLite#23]
Data reader does not parse it's results correctly. I can't imagein when I look in the DB I see an INTEGER value of 44083 that suddenly becomes 1331057912 in .NET when read using Getvalue or GetInt32.

The same goes for float and all other numeric data types. If you can't get your shit straight, get the hell out of IT. I can't imagine I'm the only one on the planet that has seen this error.

**Comment by bgrainger** [comment]
There's insufficient information in this report to reproduce the bug.

**Comment by WK-eni** [comment]
then I suggest you start monitoting yourself becues I just use your reader and van a 850 GB corruptDB

**Comment by WK-eni** [comment]
"there is not enough information so as a lazy ass developer i just close this instead of asking input" yeah that seems correct for your type of developers.

**Comment by bgrainger** [comment]
What OS?
What .NET runtime?
What version of the library?
Any sample code that reproduces the problem?

**Comment by bgrainger** [comment]
There is insufficient information in this report to reproduce the problem.
