### ISSUE TITLE
Fix build script

### ISSUE THREAD

**Issue by ejball** [Faithlife/System.Data.SQLite#27]
We could not get the psake build script to work on the machine that had Xamarin installed. For expediency, I deployed directly from the Visual Studio build.

We should switch to Cake and make it possible to deploy from the automated build.

**Comment by ejball** [comment]
We could also consider switching to https://github.com/Faithlife/FaithlifeBuild.

**Comment by bgrainger** [comment]
Done in https://github.com/Faithlife/System.Data.SQLite/commit/ca6aad109673c96c9ca4db9474abd9f19d6e448a.
