### ISSUE TITLE
Xamarin.Forms sample

### ISSUE THREAD

**Issue by Dhillu** [Faithlife/System.Data.SQLite#28]
Could you please provide a sample with password feature and detailed document on how to integrate this library with Xamarin.Forms app ? We'd like to integrate this in our Xamarin app.

**Comment by bgrainger** [comment]
No, we cannot provide a sample or tutorial.

I suggest using https://github.com/praeclarum/sqlite-net, which supports Xamarin and has a wiki with examples.

**Comment by bgrainger** [comment]
https://github.com/Achilles-Software/Entities.Sqlite may also be another good alternative.
