### ISSUE TITLE
Support URI filenames

### ISSUE THREAD

**Issue by ejball** [Faithlife/System.Data.SQLite#31]
Near as I can tell, we don't currently support [URI filenames](https://www.sqlite.org/c3ref/open.html). I think it would be as simple as setting an `openFlags` bit (`SQLITE_OPEN_URI 0x00000040`).

I was hoping to leverage ["shared cache" in-memory databases](https://www.sqlite.org/inmemorydb.html#sharedmemdb) so we could open multiple connections to the same in-memory database. (I'm not sure yet if that would require another change to this library.)

**Comment by bgrainger** [comment]
Or we could ensure that the native libraries are compiled with `SQLITE_USE_URI`.

It appears that there will be a potential conflict between `?mode=ro` in a URI filename and our `SQLiteConnectionStringBuilder.ReadOnly` property:

> It is an error to specify a value for the mode parameter that is less restrictive than that specified by the flags passed in the third parameter to sqlite3_open_v2().

User beware, perhaps.

**Comment by ejball** [comment]
Ideally the solution would work with the default native libraries provided by https://www.nuget.org/packages/SQLite/.

**Comment by ejball** [comment]
Fixed by #32.
