### ISSUE TITLE
Clean up old preprocessor directives

### ISSUE THREAD

**Issue by ejball** [Faithlife/System.Data.SQLite#36]
Few if any of the preprocessor directives are useful now that we support .NET Standard. We should remove them.

**Comment by bgrainger** [comment]
Fixed in https://github.com/Faithlife/System.Data.SQLite/commit/0ebbba20d262bc60fbbb3b11aedee413c769ba0b and https://github.com/Faithlife/System.Data.SQLite/commit/a65a12c430a1fe26c4f13b88f9884df79200e167.
