### ISSUE TITLE
Update sqlite3.dll

### ISSUE THREAD

**Issue by daniol** [Faithlife/System.Data.SQLite#42]
Currently, the version 3.25.3 is used here.
The current version of SQLite is at this time 3.33.0 ([source](https://sqlite.org/changes.html)).
The underlying library should be updated ([download page](https://sqlite.org/download.html)).

**Comment by bgrainger** [comment]
A per the [README](https://github.com/Faithlife/System.Data.SQLite/blob/69e59ac3f8d5ea9e4deaba1fc10a93b5dff4fec9/README.md#compatibility), that DLL is supplied just for the unit tests; you are expected to distribute a recent version of sqlite3.dll through some other mechanism.
